### ISSUE TITLE
 import schedule ImportError: No module named schedule

### ISSUE THREAD

**Issue by alxzanderlove** [AhmadElMelegy/Suspend-at-Prayers#1]
Traceback (most recent call last):
  File "./pray.py", line 4, in <module>
    import schedule
ImportError: No module named schedule

**Comment by mlegy** [comment]
You have to install `schedule` module. use this command:

```
pip install schedule
```

If you don't have pip installed you have to install it using this command:

```
sudo apt-get install python-pip
```

Sorry for not mentioning that.
